### ISSUE TITLE
Error when running "famous dev"

### ISSUE THREAD

**Issue by TheInvoker** [Famous/famous-cli#11]
I am installing famo.us, and I created a project, then went into the folder and ran famous dev like it says here

http://famous.org/get-started.html

but then I get an error:

Does anyone know how to fix this? (I'm on windows 7 64-bit)
Thanks

C:\Users\Me\Desktop\Apps\Messenger>famous create messenger
Seed project created at: C:\Users\Me\Desktop\Apps\Messenger\messenger

C:\Users\Me\Desktop\Apps\Messenger>cd messenger

C:\Users\Me\Desktop\Apps\Messenger\messenger>famous dev
Node Modules not yet installed, attempting to do so now.
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn npm ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)

C:\Users\Me\Desktop\Apps\Messenger\messenger>

**Comment by TusharaFernando** [comment]
I had to run
npm install -g browserify
npm install -g uglify
npm install -g uglifyjs
npm install -g watchify
npm install -g serve

and then run the commands in the packages.json directly - seems like the famous command line does not work

**Comment by jmcfet** [comment]
Do not understand how they can release a product in this state Does not give me a warm and fuzzy feeling

**Comment by talves** [comment]
Not released :smile: v0.5.0 still Beta

**Comment by jmcfet** [comment]
Sorry my bad

**Comment by wgester** [comment]
@TheInvoker @jmcfet The CLI should be fully compatible with windows as of 92fbc75a0f7409c495bf75786d82baba531d9cbf.
