### ISSUE TITLE
famous dev Should Execute Separate Task Runner

### ISSUE THREAD

**Issue by jd-carroll** [Famous/famous-cli#23]
`famous dev` should execute a separate task runner (ie Grunt / Gulp) to execute the build and perform any livereload.  The current implementation forces everyone to move away from famous-cli when they desire more advanced build steps like sass/less or integration with Cordova.

**Comment by jd-carroll** [comment]
I think we should fork the [generator-browserify](https://www.npmjs.com/package/generator-browserify) add some famous magic and then have that generator be the target of `famous init`.  This way it would give people the option of `gulp` vs `grunt` and also give them some css options (but I could also see removing the css options altogether).

The most important thing is that it would keep people in the [famous] command line and you wouldn't be lost moving between utilities.

**Comment by lorinbeer** [comment]
Hi @jd-carroll,

thanks for the issue, didn't want to think we were ignoring you.

I agree that famous dev should execute a separate task runner. generator-browserify is a great suggestion, and I think we will have the bandwidth to look seriously at implementing this functionality this week.

**Comment by jd-carroll** [comment]
Ohh famous...
