### ISSUE TITLE
famous dev Broken on Windows

### ISSUE THREAD

**Issue by jd-carroll** [Famous/famous-cli#24]
````
$ npm install -g famous-cli
$ famous init
$ famous dev
````

Navigate to: [http://localhost:1618]()
````
**This web page is not available**
ERR_CONNECTION_REFUSED
````

There are otherwise no errors/exceptions/warnings in the shell or from the window console.

**Comment by lorinbeer** [comment]
the fix is in, please let us know of any further problems
