### ISSUE TITLE
Seed Project download at "https://code.famo.us/cli/engine-seed-master.tar.gz" contains error in index.html

### ISSUE THREAD

**Issue by abyss-outpost** [Famous/famous-cli#32]
index.html reads: Line 29
\<body\>
\<script src="bundle.js"\>\</script\>
\</body\>

bundle.js doesn't exist. Please remove or fix file call from original seed project

**Comment by wgester** [comment]
@abyss-outpost The seed project is using browserify to build and bundle the src directory in the seed project. You'll have to run a build step before serving index.html. Use the `famous dev` command to run the build task and serve the public directory or check the package.json for the relevant npm scripts.
