### ISSUE TITLE
unauthorized to 'famous deploy'

### ISSUE THREAD

**Issue by vkammerer** [Famous/famous-cli#47]
When I try to run 'famous deploy', I get an 'unauthorized' error, even though I'm logged in.

Logs: https://gist.github.com/vkammerer/5a97003e95e9d6792d94

1 - What am I doing wrong?
2 - How can we improve the error messages so it isn't so obscure?

**Comment by wgester** [comment]
There was a server error, it should be working now. We can definitely improve the error message handling. Any suggestions are welcome.
