### ISSUE TITLE
CLI tool does not seem to watch nested components 

### ISSUE THREAD

**Issue by thiswildorchid** [Famous/famous-cli#54]
It appears that when I create new components the app is not watching them for changes and wont load the changes made to the files in the modules. 

### How to reproduce

- create demo app
- create new folder with `.famous` directory and `myNameSpace.js` file
- include `myNameSpace` component in main app  i.e.

```
FamousFramework.scene('thedude:magick', {
    behaviors: {
        '#surface': {
            'content': '<h1>Hello world!</h1>',
            'size': [800, 800]
        }
    },

    tree: `<node>
    <node id="surface"></node>
    <thedude:google:simple-map></thedude:google:simple-map> //my custom namespace 
    </node>`
});

```
- now modify the file in custom namespace and note that the changes are not being compiled and rendered on page reload. 

![issue](http://imagizer.imageshack.us/v2/320x240q90/537/AsCgxb.png)

**Comment by matthewtoast** [comment]
This is actually an issue with the Famous/framework dev tools. Closing this issue and re-filing it there: https://github.com/Famous/framework/issues/30
