### ISSUE TITLE
[bug] Error 404 on email confirmation page.

### ISSUE THREAD

**Issue by trusktr** [Famous/famous-cli#57]
My link is https://famous.org/v1/confirmations?confirmation_token=Vx9QhuzP-p_GsH2HeZAt

**Comment by gabz75** [comment]
Sorry about that, the domain name seems wrong, you can use this link instead:

https://api-beta.famo.us/auth/v1/confirmations?confirmation_token=Vx9QhuzP-p_GsH2HeZAt

We're working on pushing the fix asap as well.

Thanks!

**Comment by trusktr** [comment]
Cool! `{"message":"email successfully confirmed"}`

**Comment by gabz75** [comment]
The fix has been pushed, closing this issue.
