### ISSUE TITLE
`famous project deploy` should error when not authenticated

### ISSUE THREAD

**Issue by ericvicenti** [Famous/famous-cli#8]
Running deploy when not logged in does not throw an error or print any message, so I didn't know that I was supposed to run `famous register` beforehand.

```
npm install -g famous-cli
famous init my-first-project
cd my-first-project
famous project deploy
```

Node.js v0.12.1
OSX 10.10.3

**Comment by TheAlphaNerd** [comment]
the command is

```famous deploy```

can you try that and see if it helps

**Comment by lorinbeer** [comment]
we have implemented support for ghost users, as well as a warning that the user is not logged in on execution of deploy. This should resolve this issue.
